name: Test Win Installer

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build Inviwo]
    types: 
      - completed

jobs:
  test-win-installer:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest
    
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        name: inviwo-installer-win
        workflow: inviwo.yml

    - name: Run Installer
      shell: pwsh
      run: |
        # find the name of the installer
        $exe = Get-ChildItem -Name Inviwo-*.exe
        # launch the nsis installer in "silent mode" (/S), should run without user interaction
        Invoke-expression "./$exe /S"
        # this will spawn the installer in the background so we need to wait for it to finish
        $proc = Get-Process | where {$_.ProcessName -like "Inviwo-*"} | Select-Object -First 1
        if ($proc) { 
          Wait-Process -Id $proc.id
        }
        
    - name: Run Inviwo
      shell: pwsh
      run: |
        $ver = (Get-ChildItem -Name C:/"Program Files"/Inviwo/*)
        Invoke-expression "C:/'Program Files'/Inviwo/$ver/bin/Inviwo-cli.exe --logconsole --quit"
