name: Test Win Installer

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build Inviwo]
    types: 
      - completed

jobs:
  test-win-installer:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest
    
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        name: inviwo-installer-win
        workflow: inviwo.yml

    - name: Run Installer
      shell: pwsh
      run: |
        $exe = (Get-ChildItem -Name Inviwo-*.exe)
        echo $exe
        Invoke-expression "./$exe /S"
        Start-Sleep -Seconds 180
        
    - name: Run Inviwo
      shell: pwsh
      run: |
        $ver = (Get-ChildItem -Name C:/"Program Files"/Inviwo/*)
        Invoke-expression "C:/'Program Files'/Inviwo/$ver/bin/Inviwo-cli.exe --logconsole --quit"
